apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: soha-agent
resources:
  - soha-agent.yaml
commonLabels:
  app.kubernetes.io/name: soha-agent
  app.kubernetes.io/part-of: opensoha
